---
- name: "Update repositories cache"
  ansible.builtin.apt:
    update_cache: true

- name: "Install nodejs"
  ansible.builtin.apt:
    name: nodejs
    state: present

- name: "Install npm"
  ansible.builtin.apt:
    name: npm
    state: present
